language: php
php:
- '7.2'
env:
  global:
  - LINODE_HOST="69.164.211.156"
  - LINODE_USER="braican"
cache:
  yarn: true
  directories:
  - node_modules
  - vendor
before_install:
- openssl aes-256-cbc -K $encrypted_aa6afee07e57_key -iv $encrypted_aa6afee07e57_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- nvm install
install:
- yarn test
script:
- 
deploy:
  provider: script
  script: bash bin/deploy.sh
  skip_cleanup: true
  on:
    branch: setup
