language: php

php:
- '7.2'

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
  - LINODE_HOST="69.164.211.156"
  - LINODE_USER="braican"

cache:
  yarn: true
  directories:
  - node_modules
  - vendor

before_deploy:
- openssl aes-256-cbc -K $encrypted_7dcc3917ca87_key -iv $encrypted_7dcc3917ca87_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_rsa
- ssh-add .travis/deploy_rsa
- nvm install

install:
- composer install

script:
- 

deploy:
  provider: script
  script: bash bin/deploy.sh
  skip_cleanup: true
  on:
    branch: master
