language: php

php:
  - '7.2'

env:
  global:
    - LINODE_HOST="69.164.211.156"
    - LINODE_USER="braican"

cache:
  yarn: true
  directories:
    - node_modules
    - vendor

before_install:
  - nvm install

install:
  - yarn test

# script:
  # - yarn lint:scripts && yarn lint:styles

deploy:
  provider: script
  script: bash bin/deploy.sh
  skip_cleanup: true
  # on:
    # branch: master