# example netlify.toml
[build]
  command = "yarn build && yarn lambda"
  functions = "./functions" # netlify-lambda reads this
  publish = "public"

[dev]
  command = "yarn start"
  autoLaunch = false
